/* Generated By:JJTree: Do not edit this line. ASTCompOperator.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCompOperator extends SimpleNode {
  public ASTCompOperator(int id) {
    super(id);
  }

  public ASTCompOperator(MyLangParser p, int id) {
    super(p, id);
  }
  private Token token;

public void setToken(Token t) {
    this.token = t;
}

public Token getToken() {
    return token;
}



  /** Accept the visitor. **/
  public Object jjtAccept(MyLangParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d1a569ccc1bdd25b3a8e3950c6d111c5 (do not edit this line) */
