/* Generated By:JJTree: Do not edit this line. ASTInputStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTInputStatement extends SimpleNode {
  public ASTInputStatement(int id) {
    super(id);
  }

  public ASTInputStatement(MyLangParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyLangParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0114d0da2fda21d8a40eefe310099395 (do not edit this line) */
