/* Generated By:JJTree: Do not edit this line. ASTPrintable.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTPrintable extends SimpleNode {
  public ASTPrintable(int id) {
    super(id);
  }

  public ASTPrintable(MyLangParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyLangParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1659b9c109d556350091bbcd58e41c9d (do not edit this line) */
