/* Generated By:JJTree: Do not edit this line. ASTPrintableValue.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTPrintableValue extends SimpleNode {
  public ASTPrintableValue(int id) {
    super(id);
  }

  public ASTPrintableValue(MyLangParser p, int id) {
    super(p, id);
  }
  private Token token;

public void setToken(Token t) {
    this.token = t;
}

public Token getToken() {
    return token;
}


  /** Accept the visitor. **/
  public Object jjtAccept(MyLangParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=16016ee6c5b606e819c546bcc0194777 (do not edit this line) */
