/* Generated By:JJTree: Do not edit this line. ASTStringDeclaration.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTStringDeclaration extends SimpleNode {
  public ASTStringDeclaration(int id) {
    super(id);
  }

  public ASTStringDeclaration(MyLangParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyLangParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ce2c11a37f2eaccbd9d45242c2107237 (do not edit this line) */
