/* Generated By:JJTree: Do not edit this line. ASTStringLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTStringLiteral extends SimpleNode {
  public ASTStringLiteral(int id) {
    super(id);
  }

  public ASTStringLiteral(MyLangParser p, int id) {
    super(p, id);
  }
  private Token token;

public void setToken(Token t) {
    this.token = t;
}

public Token getToken() {
    return token;
}


  /** Accept the visitor. **/
  public Object jjtAccept(MyLangParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b34a6a65fb9903c7c921309693da8d9c (do not edit this line) */
