/* Generated By:JJTree: Do not edit this line. ASTVar.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTVar extends SimpleNode {
  public ASTVar(int id) {
    super(id);
  }

  public ASTVar(MyLangParser p, int id) {
    super(p, id);
  }
  private Token token;

public void setToken(Token t) {
    this.token = t;
}

public Token getToken() {
    return token;
}


  /** Accept the visitor. **/
  public Object jjtAccept(MyLangParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b164664de2a814a14993daa6ab63b63b (do not edit this line) */
