/* Generated By:JJTree&JavaCC: Do not edit this line. MyLangParserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyLangParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WENZI = 5;
  /** RegularExpression Id. */
  int CETAK = 6;
  /** RegularExpression Id. */
  int EGER = 7;
  /** RegularExpression Id. */
  int NEMESE = 8;
  /** RegularExpression Id. */
  int ULANG = 9;
  /** RegularExpression Id. */
  int KALI = 10;
  /** RegularExpression Id. */
  int SURA = 11;
  /** RegularExpression Id. */
  int LPAR = 12;
  /** RegularExpression Id. */
  int RPAR = 13;
  /** RegularExpression Id. */
  int LBRA = 14;
  /** RegularExpression Id. */
  int RBRA = 15;
  /** RegularExpression Id. */
  int SEMI = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int ASN = 18;
  /** RegularExpression Id. */
  int PLUS = 19;
  /** RegularExpression Id. */
  int EQ = 20;
  /** RegularExpression Id. */
  int NEQ = 21;
  /** RegularExpression Id. */
  int LT = 22;
  /** RegularExpression Id. */
  int GT = 23;
  /** RegularExpression Id. */
  int LE = 24;
  /** RegularExpression Id. */
  int GE = 25;
  /** RegularExpression Id. */
  int STRING = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;
  /** RegularExpression Id. */
  int VAR = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"wenzi\"",
    "\"cetak\"",
    "\"eger\"",
    "\"nemese\"",
    "\"ulang\"",
    "\"kali\"",
    "\"sura\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\"+\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "<STRING>",
    "<DIGIT>",
    "<VAR>",
  };

}
