/* Generated By:JavaCC: Do not edit this line. MyLangParserTreeConstants.java Version 4.1d1 */
public interface MyLangParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENT = 1;
  public int JJTSTRINGDECLARATION = 2;
  public int JJTASSIGNMENT = 3;
  public int JJTIFSTATEMENT = 4;
  public int JJTBLOCK = 5;
  public int JJTCONDITION = 6;
  public int JJTCOMPOPERATOR = 7;
  public int JJTPRINTSTATEMENT = 8;
  public int JJTPRINTABLE = 9;
  public int JJTLOOPSTATEMENT = 10;
  public int JJTINPUTSTATEMENT = 11;
  public int JJTEXPRESSION = 12;
  public int JJTPRINTABLEVALUE = 13;
  public int JJTSTRINGLITERAL = 14;
  public int JJTVAR = 15;


  public String[] jjtNodeName = {
    "Program",
    "Statement",
    "StringDeclaration",
    "Assignment",
    "IfStatement",
    "Block",
    "Condition",
    "CompOperator",
    "PrintStatement",
    "Printable",
    "LoopStatement",
    "InputStatement",
    "Expression",
    "PrintableValue",
    "StringLiteral",
    "Var",
  };
}
/* JavaCC - OriginalChecksum=4458aca2d92eb63cda0a1cb90512f571 (do not edit this line) */
