/* Generated By:JavaCC: Do not edit this line. MyLangParserVisitor.java Version 4.1d1 */
public interface MyLangParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTStringDeclaration node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTIfStatement node, Object data);
  public Object visit(ASTBlock node, Object data);
  public Object visit(ASTCondition node, Object data);
  public Object visit(ASTCompOperator node, Object data);
  public Object visit(ASTPrintStatement node, Object data);
  public Object visit(ASTPrintable node, Object data);
  public Object visit(ASTLoopStatement node, Object data);
  public Object visit(ASTInputStatement node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTPrintableValue node, Object data);
  public Object visit(ASTStringLiteral node, Object data);
  public Object visit(ASTVar node, Object data);
}
/* JavaCC - OriginalChecksum=bbba28755321e6aa1753a1b8e34ebbd0 (do not edit this line) */
